app: vjepa
cpus_per_task: 8
data:
  batch_size: 2
  crop_size: 256
  dataset_fpcs:
  - 16
  dataset_type: VideoDataset
  datasets:
  - /data/hyuntak/project/2026/2027_cvpr/vjepa2/data_csv/IntPhys2/IntPhys2_2way_val.csv
  datasets_weights:
  - 1.0
  fps: 4
  num_workers: 2
  patch_size: 16
  persistent_workers: false
  pin_mem: true
  tubelet_size: 2
data_aug:
  auto_augment: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 0.75
  - 1.35
  random_resize_scale:
  - 0.3
  - 1.0
  reprob: 0.0
folder: /data/hyuntak/project/2026/2027_cvpr/vjepa2/train_debug/vitl16_intphys2
loss:
  loss_exp: 1.0
mask:
- aspect_ratio:
  - 0.75
  - 1.5
  full_complement: false
  max_keep: null
  max_temporal_keep: 1.0
  num_blocks: 8
  spatial_scale:
  - 0.15
  - 0.15
  temporal_scale:
  - 1.0
  - 1.0
- aspect_ratio:
  - 0.75
  - 1.5
  full_complement: false
  max_keep: null
  max_temporal_keep: 1.0
  num_blocks: 2
  spatial_scale:
  - 0.7
  - 0.7
  temporal_scale:
  - 1.0
  - 1.0
mem_per_gpu: 80G
meta:
  dtype: bfloat16
  eval_freq: 100
  load_checkpoint: false
  read_checkpoint: /data/hyuntak/project/2026/2027_cvpr/vjepa2/checkpoint/models--facebook--vjepa2-vitl-fpc64-256/snapshots/b3c1679b7c34d3255ef3547f27c7b226aefab26f/original/model.pth
  save_every_freq: 1000
  seed: 239
  use_sdpa: true
model:
  model_name: vit_large
  pred_depth: 12
  pred_embed_dim: 384
  pred_num_heads: 12
  uniform_power: true
  use_activation_checkpointing: false
  use_mask_tokens: true
  use_rope: true
  zero_init_mask_tokens: true
nodes: 1
optimization:
  ema:
  - 0.99925
  - 0.99925
  epochs: 1
  final_lr: 0.000525
  final_weight_decay: 0.04
  ipe: 10
  ipe_scale: 1.25
  lr: 0.000525
  start_lr: 0.0001
  warmup: 2
  weight_decay: 0.04
tasks_per_node: 1
